version: '2'

services:
  bridge:
    build: .
    expose:
      - "8001"
    depends_on:
      - db
    env_file: env
  db:
    image: postgres:9.5
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
