version: '3'

services:
  bridge:
    build: .
    expose:
      - "8001"
    depends_on:
      - db
    volumes:
      - "./config:/etc/bridge"
  db:
    image: postgres:9.6
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
