#!/bin/bash
# Usage: scripts/build [command]
# Build an image for staging, production

# This makes sure the script fails on the first failing command
set -e

if [[ -z "$TRAVIS_BRANCH" ]]; then
  . ./scripts/build-image
fi
